source "https://rubygems.org"

# Jekyll core
gem "jekyll", "~> 4.3"
# Ruby >= 3 local dev server
gem "webrick", "~> 1.8"

# Plugins used by al-folio when using remote_theme
group :jekyll_plugins do
  gem "jekyll-remote-theme", "~> 0.4"
  gem "jekyll-paginate", "~> 1.1"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-feed", "~> 0.17"
  gem "jemoji", "~> 0.13"
  gem "jekyll-scholar", "~> 8.6"
end
